# Generated by Django 5.2.8 on 2025-11-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_groups', '0002_rename_partnenrgroup_partnergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=25)),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partner_groups.partnergroup')),
            ],
        ),
    ]
