# Generated by Django 4.2.26 on 2025-12-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cellphone', models.CharField(max_length=25)),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partner_groups.partnergroup')),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
