# Generated by Django 4.2.26 on 2025-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='body',
            field=models.TextField(default='Sin cuerpo'),
        ),
        migrations.AddField(
            model_name='status',
            name='head',
            field=models.CharField(default='Sin titulo', max_length=500),
        ),
    ]
