# Generated by Django 4.2.26 on 2025-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_status_body_status_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='head',
            field=models.CharField(default='Sin cabezera', max_length=500),
        ),
    ]
