# Generated by Django 4.2.26 on 2025-12-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'partner_groups',
            },
        ),
        migrations.CreateModel(
            name='PartnerGroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_groups.partnergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'partnergroups_products',
            },
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='products',
            field=models.ManyToManyField(through='partner_groups.PartnerGroupProduct', to='products.product'),
        ),
    ]
