# Generated by Django 4.2.26 on 2025-11-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnenrGroup',
            new_name='PartnerGroup',
        ),
    ]
