# Generated by Django 4.2.26 on 2025-11-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
        ('partner_groups', '0002_rename_partnenrgroup_partnergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerGroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_groups.partnergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='products',
            field=models.ManyToManyField(through='partner_groups.PartnerGroupProduct', to='products.product'),
        ),
    ]
