# Generated by Django 4.2.26 on 2025-11-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_products_product'),
        ('statuses', '0003_alter_status_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list, help_text='Lista de Correos con estado de envio')),
                ('subject', models.CharField(max_length=500)),
                ('contet', models.TextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='products.product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='statuses.status')),
            ],
        ),
    ]
