# Generated by Django 4.2.26 on 2025-12-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list, help_text='Lista de Correos con estado de envio')),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='products.product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='statuses.status')),
            ],
            options={
                'db_table': 'mails',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=5000)),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_status', to='mails.mail')),
            ],
            options={
                'db_table': 'deliveries_status',
            },
        ),
    ]
