# Generated by Django 4.2.26 on 2025-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='partner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
