# Generated by Django 4.2.26 on 2025-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
