# Generated by Django 4.2.26 on 2025-11-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_mail_creation_date_mail_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='contet',
            new_name='content',
        ),
    ]
